var commentsData = [
	{id:1, user_id:1, date:"2018-06-10 18:45", text:"Greetings, fellow colleagues. I would like to share my insights on this task. I reckon we should deal with at least half of the points in the plan without further delays. I suggest proceeding from one point to the next and notifying the rest of us with at least short notices. This way is best to keep track of who is doing what."},
	{id:2, user_id:2, date:"2018-06-12 19:40", text:"Hi, Corvo. I am sure that that's exactly what is thought best out there in Dunwall. Let's just do what we are supposed to do to get the result."},
	{id:3, user_id:3, date:"2018-06-12 20:16", text:"Whoa, Daisy. Corvo is right, though I must admit, he is often way too serious and lacks a good healthy sense of humour.<br>I'd also like to add that half of the points in the plan (btw who wrote it? I would like a long thoughtful conversation in person with the guy / lady in question. Maybe over a chessboard as well) Well, most of the points can be omitted if we rationally split the subtasks between all the parties and optimize the whole line of work."},
	{id:4, user_id:4, date:"2018-06-14 21:57", text:"Whatever you say, guys. (And Crake, I don't like chess. Though a blithesome conversation in the cafeteria is highly appreciated)."},
	{id:5, user_id:5, date:"2018-06-14 22:01", text:"There are things that you cannot solve by jumping in an X-wing and blowing something up, Daizy)))<br>Okay, guys, let's meet in person, discuss the final details of the plan and let's begin at last."},
	{id:6, user_id:4, date:"2018-06-14 22:31", text:"One more question, guys. Did you see Webix latest Kanban update? I think it can help us in planning our own work..  https://docs.webix.com/media/kanban/kanban_front.png"},
	{id:7, user_id:3, date:"2018-06-14 22:43", text:"Wow great, could you please share a link to this tool? Cannot wait for playing around with it."},
	{id:8, user_id:4, date:"2018-06-14 23:01", text:"Looks really cool. Here you are :) \nhttps://docs.webix.com/desktop__kanban_board.html"},
	{id:9, user_id:3, date:"2018-06-14 23:15", text:"Thanks a million ;)"}
];

var usersData = [
	{ id:1, value:"Corvo Attano", image: "./assets/avatar.jpg" },
	{ id:2, value:"Daisy Fitzroy", image: "./assets/james.jpg" },
	{ id:3, value:"Glenn Crake", image: "./assets/marie.jpg"  },
	{ id:4, value:"Me", image: "./assets/mike.jpg"  },
	{ id:5, value:"Leia Organa", image: "./assets/olivia.jpg"  }
];

var simpleData = [
	{id:1, date:"2018-06-10 18:45", text:"Greetings, fellow colleagues. I would like to share my insights on this task. I reckon we should deal with at least half of the points in the plan without further delays. I suggest proceeding from one point to the next and notifying the rest of us with at least short notices. This way is best to keep track of who is doing what."},
	{id:2, date:"2018-06-12 19:40", text:"Hi, is that you Corvo? I am sure that that's exactly what is thought best out there in Dunwall. Let's just do what we are supposed to do to get the result."},
	{id:3, date:"2018-06-12 20:16", text:"Whoa. Corvo is right, though I must admit, he is often way too serious and lacks a good healthy sense of humour.<br>I'd also like to add that half of the points in the plan (btw who wrote it? I would like a long thoughtful conversation in person with the guy / lady in question. Maybe over a chessboard as well) Well, most of the points can be omitted if we rationally split the subtasks between all the parties and optimize the whole line of work."},
	{id:4, date:"2018-06-14 21:57", text:"Whatever you say, guys. (And Crake, I don't like chess. Though a blithesome conversation in the cafeteria is highly appreciated)."},
	{id:5, date:"2018-06-14 22:01", text:"There are things that you cannot solve by jumping in an X-wing and blowing something up, Daizy))) Was it you, Daisy?<br>Okay, guys, let's meet in person, discuss the finale details of the plan and let's begin at last."}
];

var mentionedData = [
	{id:1, user_id:1, date:"2018-06-10 18:45", text:"Greetings, fellow colleagues. I would like to share my insights on this task. I reckon we should deal with at least half of the points in the plan without further delays. I suggest proceeding from one point to the next and notifying the rest of us with at least short notices. This way is best to keep track of who is doing what."},
	{id:2, user_id:2, date:"2018-06-12 19:40", text:"Hi, @Corvo Attano. I am sure that that's exactly what is thought best out there in Dunwall. Let's just do what we are supposed to do to get the result."},
	{id:3, user_id:3, date:"2018-06-12 20:16", text:"@Daisy Fitzroy. @Corvo Attano is right, though I must admit, he is often way too serious and lacks a good healthy sense of humour.<br>I'd also like to add that half of the points in the plan (btw who wrote it? I would like a long thoughtful conversation in person with the guy / lady in question. Maybe over a chessboard as well) Well, most of the points can be omitted if we rationally split the subtasks between all the parties and optimize the whole line of work."},
	{id:4, user_id:4, date:"2018-06-14 21:57", text:"Whatever you say, guys. (And @Glenn Crake, I don't like chess. Though a blithesome conversation in the cafeteria is highly appreciated)."},
	{id:5, user_id:5, date:"2018-06-14 22:01", text:"There are things that you cannot solve by jumping in an X-wing and blowing something up, Daizy)))<br>Okay, guys, let's meet in person, discuss the final details of the plan and let's begin at last."},
	{id:6, user_id:4, date:"2018-06-14 22:31", text:"One more question, guys. Did you see Webix latest Kanban update? I think it can help us in planning our own work..  https://docs.webix.com/media/kanban/kanban_front.png"},
	{id:7, user_id:3, date:"2018-06-14 22:43", text:"Wow great, could you please share a link to this tool? Cannot wait for playing around with it."},
	{id:8, user_id:4, date:"2018-06-14 23:01", text:"Looks really cool. Here you are :) \nhttps://docs.webix.com/desktop__kanban_board.html"},
	{id:9, user_id:3, date:"2018-06-14 23:15", text:"Thanks a million ;)"}
];

var films = [{"id":1,"title":"The Shawshank Redemption","year":"1994","votes":"678.79","rating":"9.2","rank":"1"},{"id":2,"title":"The Godfather","year":"1972","votes":"511.495","rating":"9.2","rank":"2"},{"id":3,"title":"The Godfather: Part II","year":"1974","votes":"319.352","rating":"9","rank":"3"},{"id":4,"title":"The Good, the Bad and the Ugly","year":"1966","votes":"213.03","rating":"8.9","rank":"4"},{"id":5,"title":"Pulp Fiction","year":"1994","votes":"533.848","rating":"8.9","rank":"5"},{"id":6,"title":"12 Angry Men","year":"1957","votes":"164.558","rating":"8.9","rank":"6"},{"id":7,"title":"Schindler's List","year":"1993","votes":"355.638","rating":"8.9","rank":"7"},{"id":8,"title":"One Flew Over the Cuckoo's Nest","year":"1975","votes":"283.176","rating":"8.8","rank":"8"},{"id":9,"title":"The Dark Knight","year":"2008","votes":"612.37","rating":"8.8","rank":"9"},{"id":10,"title":"The Lord of the Rings: The Return of the Kin","year":"2003","votes":"472.843","rating":"8.8","rank":"10"},{"id":11,"title":"Star Wars: Episode V - The Empire Strikes Bac","year":"1980","votes":"348.012","rating":"8.8","rank":"11"},{"id":12,"title":"Inception","year":"2010","votes":"458.693","rating":"8.8","rank":"12"},{"id":13,"title":"Fight Club","year":"1999","votes":"507.723","rating":"8.8","rank":"13"},{"id":14,"title":"Seven Samurai","year":"1954","votes":"118.925","rating":"8.8","rank":"14"},{"id":15,"title":"Goodfellas","year":"1990","votes":"299.349","rating":"8.7","rank":"15"},{"id":16,"title":"The Lord of the Rings: The Fellowship of the Rin","year":"2001","votes":"494.003","rating":"8.7","rank":"16"},{"id":17,"title":"Star Wars","year":"1977","votes":"393.087","rating":"8.7","rank":"17"},{"id":18,"title":"City of God","year":"2002","votes":"222.818","rating":"8.7","rank":"18"},{"id":19,"title":"Casablanca","year":"1942","votes":"202.051","rating":"8.7","rank":"19"},{"id":20,"title":"Once Upon a Time in the West","year":"1968","votes":"97.931","rating":"8.7","rank":"20"},{"id":21,"title":"The Matrix","year":"1999","votes":"492.325","rating":"8.7","rank":"21"},{"id":22,"title":"Rear Window","year":"1954","votes":"148.162","rating":"8.7","rank":"22"},{"id":23,"title":"Raiders of the Lost Ark","year":"1981","votes":"300.252","rating":"8.7","rank":"23"},{"id":24,"title":"The Silence of the Lambs","year":"1991","votes":"324.419","rating":"8.7","rank":"24"},{"id":25,"title":"The Usual Suspects","year":"1995","votes":"331.99","rating":"8.7","rank":"25"},{"id":26,"title":"Psycho","year":"1960","votes":"182.319","rating":"8.6","rank":"26"},{"id":27,"title":"Se7en","year":"1995","votes":"380.479","rating":"8.6","rank":"27"},{"id":28,"title":"Forrest Gump","year":"1994","votes":"416.066","rating":"8.6","rank":"28"},{"id":29,"title":"The Lord of the Rings: The Two Towers","year":"2002","votes":"423.855","rating":"8.6","rank":"29"}];