package b4j.example;


import anywheresoftware.b4a.BA;

public class pgcharts extends Object{
public static pgcharts mostCurrent = new pgcharts();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.pgcharts", null);
		ba.loadHtSubs(pgcharts.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.pgcharts", ba);
		}
	}
    public static Class<?> getObject() {
		return pgcharts.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static b4j.example.wixpage _pg = null;
public static b4j.example.main _main = null;
public static b4j.example.pgdataentry _pgdataentry = null;
public static b4j.example.pgforms1 _pgforms1 = null;
public static b4j.example.pgforms _pgforms = null;
public static b4j.example.pgtoolbar _pgtoolbar = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.pgmultiview _pgmultiview = null;
public static b4j.example.pglayouts1 _pglayouts1 = null;
public static b4j.example.pglayouts2 _pglayouts2 = null;
public static b4j.example.pglayouts _pglayouts = null;
public static b4j.example.pgdatatable _pgdatatable = null;
public static b4j.example.pglayout _pglayout = null;
public static String  _init() throws Exception{
anywheresoftware.b4a.objects.collections.List _chartdata = null;
b4j.example.wixrow _r1 = null;
b4j.example.wixchart _wchart = null;
b4j.example.wixchart _w1 = null;
b4j.example.wixchart _w2 = null;
b4j.example.wixrow _r2 = null;
b4j.example.wixchart _w3 = null;
b4j.example.wixchart _w4 = null;
b4j.example.wixchart _w5 = null;
b4j.example.wixrow _r3 = null;
b4j.example.wixchart _w6 = null;
b4j.example.wixchart _w7 = null;
b4j.example.wixchart _w8 = null;
b4j.example.wixchart _w9 = null;
 //BA.debugLineNum = 6;BA.debugLine="Sub Init";
 //BA.debugLineNum = 7;BA.debugLine="pg.Initialize(\"\").SetHeader(\"Lesson 7: WixCharts\"";
_pg._initialize /*b4j.example.wixpage*/ (ba,"")._setheader /*b4j.example.wixpage*/ ("Lesson 7: WixCharts");
 //BA.debugLineNum = 9;BA.debugLine="Dim chartData As List";
_chartdata = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 10;BA.debugLine="chartData.Initialize";
_chartdata.Initialize();
 //BA.debugLineNum = 11;BA.debugLine="chartData.Add(CreateMap(\"count\" : 65, \"dollars\" :";
_chartdata.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("count"),(Object)(65),(Object)("dollars"),(Object)(130),(Object)("color"),(Object)("#ff0000"),(Object)("type"),(Object)("AA")}).getObject()));
 //BA.debugLineNum = 12;BA.debugLine="chartData.Add(CreateMap(\"count\" : 120, \"dollars\"";
_chartdata.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("count"),(Object)(120),(Object)("dollars"),(Object)(280),(Object)("color"),(Object)("#00ff00"),(Object)("type"),(Object)("BB")}).getObject()));
 //BA.debugLineNum = 13;BA.debugLine="chartData.Add(CreateMap(\"count\" : 50, \"dollars\" :";
_chartdata.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("count"),(Object)(50),(Object)("dollars"),(Object)(98),(Object)("color"),(Object)("#0000ff"),(Object)("type"),(Object)("CC")}).getObject()));
 //BA.debugLineNum = 14;BA.debugLine="chartData.Add(CreateMap(\"count\" : 90, \"dollars\" :";
_chartdata.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("count"),(Object)(90),(Object)("dollars"),(Object)(110),(Object)("color"),(Object)("#ffff00"),(Object)("type"),(Object)("DD")}).getObject()));
 //BA.debugLineNum = 16;BA.debugLine="pg.Page.AddRows(CreateMap(\"height\":10))";
_pg._page /*b4j.example.wixelement*/ ._addrows /*b4j.example.wixelement*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("height"),(Object)(10)}));
 //BA.debugLineNum = 18;BA.debugLine="Dim R1 As WixRow";
_r1 = new b4j.example.wixrow();
 //BA.debugLineNum = 19;BA.debugLine="R1.Initialize(\"\")";
_r1._initialize /*b4j.example.wixrow*/ (ba,"");
 //BA.debugLineNum = 21;BA.debugLine="R1.AddColumns(CreateMap(\"width\":10))";
_r1._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 22;BA.debugLine="Dim wchart As WixChart";
_wchart = new b4j.example.wixchart();
 //BA.debugLineNum = 23;BA.debugLine="wchart.Initialize(\"\").SetTypeArea(\"\").SetValue(\"#";
_wchart._initialize /*b4j.example.wixchart*/ (ba,"")._settypearea /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 24;BA.debugLine="R1.AddColumns(wchart.Item)";
_r1._addcolumns /*b4j.example.wixrow*/ (_wchart._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 26;BA.debugLine="R1.AddColumns(CreateMap(\"width\":10))";
_r1._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 27;BA.debugLine="Dim w1 As WixChart";
_w1 = new b4j.example.wixchart();
 //BA.debugLineNum = 28;BA.debugLine="w1.Initialize(\"\").SetTypeBar(\"\").SetValue(\"#count";
_w1._initialize /*b4j.example.wixchart*/ (ba,"")._settypebar /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 29;BA.debugLine="w1.SetBarWidth(100).SetRadius(10).SetGradient(\"3d";
_w1._setbarwidth /*b4j.example.wixchart*/ ((int) (100))._setradius /*b4j.example.wixchart*/ ((int) (10))._setgradient /*b4j.example.wixchart*/ ("3d");
 //BA.debugLineNum = 30;BA.debugLine="R1.AddColumns(w1.Item)";
_r1._addcolumns /*b4j.example.wixrow*/ (_w1._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 32;BA.debugLine="R1.AddColumns(CreateMap(\"width\":10))";
_r1._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 33;BA.debugLine="Dim w2 As WixChart";
_w2 = new b4j.example.wixchart();
 //BA.debugLineNum = 34;BA.debugLine="w2.Initialize(\"\").SetTypeBarH(\"\").SetValue(\"#coun";
_w2._initialize /*b4j.example.wixchart*/ (ba,"")._settypebarh /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 35;BA.debugLine="w2.SetBarWidth(20).SetRadius(10).SetGradient(\"fal";
_w2._setbarwidth /*b4j.example.wixchart*/ ((int) (20))._setradius /*b4j.example.wixchart*/ ((int) (10))._setgradient /*b4j.example.wixchart*/ ("falling")._setpadding /*b4j.example.wixchart*/ ((int) (40));
 //BA.debugLineNum = 36;BA.debugLine="R1.AddColumns(w2.Item)";
_r1._addcolumns /*b4j.example.wixrow*/ (_w2._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 37;BA.debugLine="R1.AddColumns(CreateMap())";
_r1._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {}));
 //BA.debugLineNum = 39;BA.debugLine="pg.Page.AddRow(R1)";
_pg._page /*b4j.example.wixelement*/ ._addrow /*String*/ (_r1);
 //BA.debugLineNum = 41;BA.debugLine="pg.Page.AddRows(CreateMap(\"height\":10))";
_pg._page /*b4j.example.wixelement*/ ._addrows /*b4j.example.wixelement*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("height"),(Object)(10)}));
 //BA.debugLineNum = 42;BA.debugLine="Dim R2 As WixRow";
_r2 = new b4j.example.wixrow();
 //BA.debugLineNum = 43;BA.debugLine="R2.Initialize(\"\")";
_r2._initialize /*b4j.example.wixrow*/ (ba,"");
 //BA.debugLineNum = 45;BA.debugLine="R2.AddColumns(CreateMap(\"width\":10))";
_r2._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 46;BA.debugLine="Dim w3 As WixChart";
_w3 = new b4j.example.wixchart();
 //BA.debugLineNum = 47;BA.debugLine="w3.Initialize(\"\").SetTypeDonut(\"\").SetValue(\"#cou";
_w3._initialize /*b4j.example.wixchart*/ (ba,"")._settypedonut /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setcolor /*b4j.example.wixchart*/ ("#color#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setdata /*b4j.example.wixchart*/ (_chartdata)._setshadow /*b4j.example.wixchart*/ ((int) (20));
 //BA.debugLineNum = 48;BA.debugLine="w3.SetWidth(300).SetHeight(200)";
_w3._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200));
 //BA.debugLineNum = 50;BA.debugLine="R2.AddColumns(w3.Item)";
_r2._addcolumns /*b4j.example.wixrow*/ (_w3._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 52;BA.debugLine="R2.AddColumns(CreateMap(\"width\":10))";
_r2._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 53;BA.debugLine="Dim w4 As WixChart";
_w4 = new b4j.example.wixchart();
 //BA.debugLineNum = 54;BA.debugLine="w4.Initialize(\"\").SetTypeLine(\"\").SetValue(\"#coun";
_w4._initialize /*b4j.example.wixchart*/ (ba,"")._settypeline /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 55;BA.debugLine="w4.SetLine(\"#ffa0d0\",10)";
_w4._setline /*b4j.example.wixchart*/ ("#ffa0d0",(int) (10));
 //BA.debugLineNum = 56;BA.debugLine="R2.AddColumns(w4.Item)";
_r2._addcolumns /*b4j.example.wixrow*/ (_w4._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 58;BA.debugLine="R2.AddColumns(CreateMap(\"width\":10))";
_r2._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 59;BA.debugLine="Dim w5 As WixChart";
_w5 = new b4j.example.wixchart();
 //BA.debugLineNum = 60;BA.debugLine="w5.Initialize(\"\").SetTypePie(\"\").SetValue(\"#count";
_w5._initialize /*b4j.example.wixchart*/ (ba,"")._settypepie /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setcolor /*b4j.example.wixchart*/ ("#color#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 61;BA.debugLine="w5.SetShadow(20).SetLegend(90,\"right\")";
_w5._setshadow /*b4j.example.wixchart*/ ((int) (20))._setlegend /*b4j.example.wixchart*/ ((int) (90),(int)(Double.parseDouble("right")));
 //BA.debugLineNum = 62;BA.debugLine="R2.AddColumns(w5.Item)";
_r2._addcolumns /*b4j.example.wixrow*/ (_w5._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 63;BA.debugLine="R2.AddColumns(CreateMap())";
_r2._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {}));
 //BA.debugLineNum = 65;BA.debugLine="pg.Page.AddRow(R2)";
_pg._page /*b4j.example.wixelement*/ ._addrow /*String*/ (_r2);
 //BA.debugLineNum = 66;BA.debugLine="pg.Page.AddRows(CreateMap(\"height\":10))";
_pg._page /*b4j.example.wixelement*/ ._addrows /*b4j.example.wixelement*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("height"),(Object)(10)}));
 //BA.debugLineNum = 68;BA.debugLine="Dim R3 As WixRow";
_r3 = new b4j.example.wixrow();
 //BA.debugLineNum = 69;BA.debugLine="R3.Initialize(\"\")";
_r3._initialize /*b4j.example.wixrow*/ (ba,"");
 //BA.debugLineNum = 70;BA.debugLine="R3.AddColumns(CreateMap(\"width\":10))";
_r3._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 71;BA.debugLine="Dim w6 As WixChart";
_w6 = new b4j.example.wixchart();
 //BA.debugLineNum = 72;BA.debugLine="w6.Initialize(\"\").SetTypePie3D(\"\").SetValue(\"#cou";
_w6._initialize /*b4j.example.wixchart*/ (ba,"")._settypepie3d /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setcolor /*b4j.example.wixchart*/ ("#color#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 73;BA.debugLine="R3.AddColumns(w6.Item)";
_r3._addcolumns /*b4j.example.wixrow*/ (_w6._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 75;BA.debugLine="R3.AddColumns(CreateMap(\"width\":10))";
_r3._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 76;BA.debugLine="Dim w7 As WixChart";
_w7 = new b4j.example.wixchart();
 //BA.debugLineNum = 77;BA.debugLine="w7.Initialize(\"\").SetTypeStackedArea(\"\").SetValue";
_w7._initialize /*b4j.example.wixchart*/ (ba,"")._settypestackedarea /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setcolor /*b4j.example.wixchart*/ ("#color#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 78;BA.debugLine="R3.AddColumns(w7.Item)";
_r3._addcolumns /*b4j.example.wixrow*/ (_w7._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 80;BA.debugLine="R3.AddColumns(CreateMap(\"width\":10))";
_r3._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 81;BA.debugLine="Dim w8 As WixChart";
_w8 = new b4j.example.wixchart();
 //BA.debugLineNum = 82;BA.debugLine="w8.Initialize(\"\").SetTypeSpline(\"\").SetValue(\"#co";
_w8._initialize /*b4j.example.wixchart*/ (ba,"")._settypespline /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setcolor /*b4j.example.wixchart*/ ("#color#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 83;BA.debugLine="R3.AddColumns(w8.Item)";
_r3._addcolumns /*b4j.example.wixrow*/ (_w8._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 86;BA.debugLine="R3.AddColumns(CreateMap(\"width\":10))";
_r3._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("width"),(Object)(10)}));
 //BA.debugLineNum = 87;BA.debugLine="Dim w9 As WixChart";
_w9 = new b4j.example.wixchart();
 //BA.debugLineNum = 88;BA.debugLine="w9.Initialize(\"\").SetStackedBarH(\"\").SetValue(\"#c";
_w9._initialize /*b4j.example.wixchart*/ (ba,"")._setstackedbarh /*b4j.example.wixchart*/ ("")._setvalue /*b4j.example.wixchart*/ ("#count#")._setlabel /*b4j.example.wixchart*/ ("#count#")._setcolor /*b4j.example.wixchart*/ ("#color#")._setwidth /*b4j.example.wixchart*/ ((int) (300))._setheight /*b4j.example.wixchart*/ ((int) (200))._setdata /*b4j.example.wixchart*/ (_chartdata);
 //BA.debugLineNum = 89;BA.debugLine="w9.SetRadius(10).SetShadow(\"falling\")";
_w9._setradius /*b4j.example.wixchart*/ ((int) (10))._setshadow /*b4j.example.wixchart*/ ((int)(Double.parseDouble("falling")));
 //BA.debugLineNum = 90;BA.debugLine="R3.AddColumns(w9.Item)";
_r3._addcolumns /*b4j.example.wixrow*/ (_w9._item /*anywheresoftware.b4a.objects.collections.Map*/ ());
 //BA.debugLineNum = 91;BA.debugLine="R3.AddColumns(CreateMap())";
_r3._addcolumns /*b4j.example.wixrow*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {}));
 //BA.debugLineNum = 93;BA.debugLine="pg.Page.AddRow(R3)";
_pg._page /*b4j.example.wixelement*/ ._addrow /*String*/ (_r3);
 //BA.debugLineNum = 94;BA.debugLine="pg.Page.AddRows(CreateMap(\"height\":10))";
_pg._page /*b4j.example.wixelement*/ ._addrows /*b4j.example.wixelement*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("height"),(Object)(10)}));
 //BA.debugLineNum = 97;BA.debugLine="pg.ui";
_pg._ui /*String*/ ();
 //BA.debugLineNum = 98;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Private pg As WixPage";
_pg = new b4j.example.wixpage();
 //BA.debugLineNum = 4;BA.debugLine="End Sub";
return "";
}
}
