B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=StaticCode
Version=7.51
@EndOfDesignText@
Sub Process_Globals
End Sub

Sub BuildBag(Page As WixPage, Bag As WixProperty)
	Bag.Clear
	Bag.AddTextBox("id", "ID", "datatable1")
	Bag.AddTextBox("localId", "Local ID", "")
	Bag.AddLabel("Parent")
	Bag.AddTextBox("parentid","Parent", "form")
	Bag.AddCombo("addingmethod","Adding Method","AddRows", pgFD.addingmethod)
	Bag.AddTextBox("tabindex", "Tab Index", "0")
	Bag.AddCombo("view","View", "datatable", Page.Views)
	Bag.AddLabel("Details")
	Bag.AddTextBox("animate","Animate", "")
	Bag.AddCheckBox("areaselect","Area Select", "")
	Bag.AddCheckBox("autoConfig","Auto Config", "")
	Bag.AddCheckBox("autoheight","Auto Height", "")
	Bag.AddCheckBox("autowidth","Auto Width", "")
	Bag.AddCombo("blockselect", "Block Select", "", Array("","true","box","select","false"))
	Bag.AddCheckBox("borderless","Borderless", "")
	Bag.AddCheckBox("checkboxRefresh","Checkbox Refresh", "")
	Bag.AddCombo("clipboard", "Clipboard", "", Array("","block","true","selection","repeat","false","custom"))
	Bag.AddTextBox("columnWidth","Column Width", "")
	Bag.AddTextBox("container","Container", "")
	Bag.AddTextBox("css","Css", "")
	Bag.AddTextBox("data","Data", "")
	Bag.AddTextBox("dataFeed","Data Feed", "")
	Bag.AddTextBox("datafetch","Data Fetch", "")
	Bag.AddTextBox("datathrottle","Data Throttle", "")
	Bag.AddCombo("datatype", "Data Type", "", Array("","json","xml","jsarray","csv"))
	Bag.AddTextBox("delimiter","Delimiter", "")
	Bag.AddCheckBox("disabled","Disabled", "")
	Bag.AddCombo("drag", "Drag", "", Array("","true","order","move","inner","source","target","false"))
	Bag.AddCombo("dragColumn", "Drag Column", "", Array("","true","false","order"))
	Bag.AddCombo("dragscroll", "Drag Scroll", "", Array("","x","y","true","xy","false"))
	Bag.AddCheckBox("editMath","Edit Math", "")
	Bag.AddTextBox("editValue","Edit Value", "")
	Bag.AddCheckBox("editable","Editable", "")
	Bag.AddTextBox("filterMode","Filter Mode", "")
	Bag.AddCheckBox("fixedRowHeight","Fixed Row Height", "")
	Bag.AddCheckBox("footer","Footer", "")
	Bag.AddTextBox("form","Form", "")
	Bag.AddTextBox("gravity","Gravity", "")
	Bag.AddCheckBox("header","Header", "")
	Bag.AddTextBox("headerRowHeight","Header Row Height", "")
	Bag.AddCheckBox("headermenu","Header Menu", "")
	Bag.AddTextBox("height","Height", "")
	Bag.AddCheckBox("hidden","Hidden", "")
	Bag.AddTextBox("hover","Hover", "")
	Bag.AddTextBox("leftSplit","Left Split", "")
	Bag.AddCheckBox("lineValidation","Line Validation", "")
	Bag.AddTextBox("loadahead","Load Ahead", "")
	Bag.AddCheckBox("math","Math", "")
	Bag.AddTextBox("maxHeight","Max Height", "")
	Bag.AddTextBox("maxWidth","Max Width", "")
	Bag.AddTextBox("minColumnWidth","Min Column Width", "")
	Bag.AddTextBox("minHeight","Min Height", "")
	Bag.AddTextBox("minRowHeight","Min Row Height", "")
	Bag.AddTextBox("minWidth","Min Width", "")
	Bag.AddCheckBox("multiselect","Multi Select", "")
	Bag.AddCheckBox("navigation","Navigation", "")
	Bag.AddTextBox("pager","Pager", "")
	Bag.AddCheckBox("prerender","Pre Render", "")
	Bag.AddCheckBox("resizeColumn","Resize Column", "")
	Bag.AddCheckBox("resizeRow","Resize Row", "")
	Bag.AddTextBox("rightSplit","Right Split", "")
	Bag.AddTextBox("rowHeight","Row Height", "")
	Bag.AddTextBox("rowLineHeight","Row Line Height", "")
	Bag.AddTextBox("save","Save", "")
	Bag.AddCombo("scroll", "Scroll", "", Array("","y","true","xy","false"))
	Bag.AddCheckBox("scrollAlignY","Scroll Align Y", "")
	Bag.AddCheckBox("scrollX","Scroll X", "")
	Bag.AddCheckBox("scrollY","Scroll Y", "")
	Bag.AddCombo("select", "Select", "", Array("","cell","row","column","true","false"))
	Bag.AddTextBox("tooltip","Tooltip", "")
	Bag.AddTextBox("topSplit","Top Split", "")
	Bag.AddCheckBox("undo","Undo", "")
	Bag.AddTextBox("url","Url", "")
	Bag.AddTextBox("width","Width", "")
	Bag.AddTextBox("yCount","Y Count", "")
	Bag.Refresh(Page)
End Sub